version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: analitycPostgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles: [ "monitor" ]
    ports:
      - "9090:9090"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge