global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'geekshubs'

remote_write:
  - url: http://cortex:9009/api/prom/push

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9091']
